Repository SystemConsultantGroup/S-top-frontend, pull requests merged in 2024-11, with the labels that each got.

#105 [Feat] 회원가입 페이지 구현 완료
  src/components/common/CheckBox/CheckBox.tsx
  src/components/common/RegisterForm/registerForm.module.css
  src/components/common/RegisterForm/registerForm.tsx
  src/components/common/SearchInput/SearchInput.tsx
Labels: feat

#102 [FIX] 파일 업로드 api 수정
  src/hooks/useFiles/useFiles.ts
Labels: fix

#109 [FEAT] 관리자 퀴즈 결과 목록 페이지 추가
  src/app/(admin)/admin/(contents)/quiz-list/page.tsx
  src/components/pages/AdminQuizListSection/AdminQuizListSection.tsx
  src/constants/DataTableHeaders.ts
  src/hooks/swr/useQuizResults.tsx
  src/types/quiz.ts
Labels: feat

#110 [FEAT] 프로젝트 문의 페이지 추가
  src/app/(admin)/admin/projects/inquiries/[id]/page.tsx
  src/app/(admin)/admin/projects/inquiries/page.tsx
  src/components/common/TitleRow/TitleRow.module.css
  src/components/common/TitleRow/TitleRow.tsx
  src/components/pages/AdminInquiriesEditForm/AdminInquiriesEditForm.tsx
  src/components/pages/AdminInquiriesListSection/AdminInquiriesListSection.tsx
  src/constants/DataTableHeaders.ts
  src/hooks/swr/useInquiries.tsx
  src/types/inquiry.ts
Labels: feat

#87 [FIX] 텍스트 입력 수정
  src/components/common/TextInput/TextInput.module.css
  src/components/common/TextInput/TextInput.tsx
Labels: fix

#112 [FIX] 공지사항 컴포넌트 및 페이지 수정
  src/app/(user)/event/notices/EventNoticesPage.tsx
  src/app/(user)/event/notices/[id]/GetUserEventDetail.ts
  src/app/(user)/event/notices/[id]/page.tsx
  src/app/(user)/event/notices/page.tsx
  src/app/(user)/infodesk/notices/NoticesPage.tsx
  src/app/(user)/infodesk/notices/[id]/GetUserNoticeDetail.ts
  src/app/(user)/infodesk/notices/[id]/page.tsx
  src/app/(user)/infodesk/notices/page.tsx
  src/components/common/NoticeDetail/NoticeDetail.module.css
  src/components/common/NoticeDetail/NoticeDetail.story.tsx
  src/components/common/NoticeDetail/NoticeDetail.test.tsx
  src/components/common/NoticeDetail/NoticeDetail.tsx
  src/components/common/NoticeDetail/elements/FileDropdownMenu.tsx
  src/components/common/NoticeDetail/elements/NoticeDetailHead.tsx
  src/components/common/NoticeDetail/elements/NoticeDetailSprint.tsx
  src/components/common/NoticeDetail/elements/NoticeDetailStage.tsx
  src/components/common/NoticeDetail/elements/NoticeDetailToolbar.tsx
  src/components/common/Noticeboard/Noticeboard.module.css
  src/components/common/Noticeboard/Noticeboard.story.tsx
  src/components/common/Noticeboard/Noticeboard.test.tsx
  src/components/common/Noticeboard/Noticeboard.tsx
  src/components/common/Noticeboard/elements/NoticeContainer.tsx
  src/components/common/Noticeboard/elements/NoticeHeading.tsx
  src/components/common/Noticeboard/elements/NoticeItem.tsx
  src/components/pages/UserBoard/UserBoard.module.css
  src/components/pages/UserBoard/UserBoard.story.tsx
  src/components/pages/UserBoard/UserBoard.tsx
  src/components/pages/UserBoard/index.ts
  src/types/PageBoardTypes.ts
  src/types/notice.ts
  src/utils/UserBoard/GetUserBoardItems.ts
  src/utils/handleDownloadFile/handleDownloadClick.ts
  src/utils/handleDownloadFile/index.ts
Labels: feat, fix

#113 [fix] 프로젝트카드 클릭 핸들러 추가
  package.json
  src/components/common/ProjectCard/ProjectCard.tsx
  src/components/common/ProjectCard/ProjectCardLikeSection.tsx
  src/components/common/TextInput/TextInput.tsx
  src/components/pages/AdminProjectsEditSection/ProjectCreateSection.tsx
  src/components/pages/AdminProjectsListSection/AdminProjectsListRow.tsx
  src/constants/DataTableHeaders.ts
  src/hooks/useFiles/useFiles.ts
Labels: bug, fix

#114 [FIX] noticeboard component 수정
  src/components/common/Noticeboard/Noticeboard.tsx
  src/theme/AppTheme.ts
Labels: fix
