Repository SystemConsultantGroup/S-top-frontend, pull requests merged in 2024-09, with the labels that each got.

#93 [FEAT] 공통 유틸함수 수정 및 추가
  src/utils/fetcher/fetcher.ts
  src/utils/fetcher/index.ts
  src/utils/handleDownloadFile/handleDownloadFile.ts
  src/utils/handleDownloadFile/index.ts
Labels: enhancement, feat

#66 [FEAT] 공지사항 & 이벤트 공지사항 전체 및 상세
  src/app/(user)/event/notices/EventNoticesPage.tsx
  src/app/(user)/event/notices/[id]/GetUserEventDetail.ts
  src/app/(user)/event/notices/[id]/page.tsx
  src/app/(user)/event/notices/page.tsx
  src/app/(user)/infodesk/notices/NoticesPage.tsx
  src/app/(user)/infodesk/notices/[id]/GetUserNoticeDetail.ts
  src/app/(user)/infodesk/notices/[id]/page.tsx
  src/app/(user)/infodesk/notices/page.tsx
  src/components/common/Header/Header.module.css
  src/components/common/NoticeDetail/NoticeDetail.tsx
  src/components/common/NoticeDetail/elements/FileDropdownMenu.tsx
  src/components/common/NoticeDetail/elements/NoticeDetailHead.tsx
  src/components/common/NoticeDetail/elements/NoticeDetailSprint.tsx
  src/components/common/NoticeDetail/elements/NoticeDetailStage.tsx
  src/components/common/NoticeDetail/elements/NoticeDetailToolbar.tsx
  src/components/common/Noticeboard/elements/NoticeHeading.tsx
  src/components/common/Pagination/Pagination.tsx
  src/components/common/SubHeadNavbar/SubHeadNavbar.tsx
  src/components/pages/UserBoard/UserBoard.module.css
  src/components/pages/UserBoard/UserBoard.story.tsx
  src/components/pages/UserBoard/UserBoard.tsx
  src/components/pages/UserBoard/index.ts
  src/styles/UserBoard.module.css
  src/types/PageBoardTypes.ts
  src/utils/UserBoard/GetUserBoardItems.ts
Labels: feat

#94 [FIX] 잡페어 배너 추가
  public/images/job-fair.png
  src/components/common/Banner/Banner.tsx
Labels: fix

#85 [FEAT] 작품 수상 결과 페이지 추가
  src/app/(user)/event/award/page.module.css
  src/app/(user)/event/award/page.tsx
  src/app/layout.tsx
  src/components/common/Pagination/Pagination.tsx
  src/components/pages/EventAwardView/EventAwardView.module.css
  src/components/pages/EventAwardView/EventAwardView.tsx
  src/components/pages/EventAwardView/_mock/mock-awards.ts
Labels: feat

#73 [FEAT] 프로젝트 상세조회 페이지 구현
  public/images/_mock/project-poster.png
  public/images/_mock/project-thumbnail.png
  src/app/(user)/projects/[id]/page.module.css
  src/app/(user)/projects/[id]/page.tsx
  src/components/common/CommentBox/CommentBox.module.css
  src/components/common/CommentBox/CommentBox.tsx
  src/components/pages/.gitkeep
  src/components/pages/ProjectDetail/ProjectDetailComment.tsx
  src/components/pages/ProjectDetail/ProjectDetailInfo.module.css
  src/components/pages/ProjectDetail/ProjectDetailInfo.tsx
  src/components/pages/ProjectDetail/ProjectDetailInquiry.tsx
  src/components/pages/ProjectDetail/_mock/mock-project.ts
  src/components/pages/ProjectDetail/index.ts
Labels: feat

#98 [FIX] Dropdown 오른쪽 화살표 색상 적용
  src/components/common/Dropdown/Dropdown.tsx
Labels: fix

#72 [Feat] 회원가입 페이지
  src/app/(user)/(auth)/login/page.tsx
  src/app/(user)/(auth)/register/page.tsx
  src/app/(user)/(auth)/register/registerPage.module.css
  src/components/common/LoginBox/LoginBox.module.css
  src/components/common/LoginBox/LoginBox.story.tsx
  src/components/common/LoginBox/LoginBox.tsx
  src/components/common/LoginBox/index.ts
  src/components/common/RegisterForm/registerForm.module.css
  src/components/common/RegisterForm/registerForm.tsx
  src/components/pages/loginPage/loginPage.module.css
  src/components/pages/loginPage/loginPage.story.tsx
  src/components/pages/loginPage/loginPage.tsx
Labels: feat

#78 [FEAT] AI Hub 페이지 (datasets and models)
  src/app/(user)/aihub/datasets/AIHub.module.css
  src/app/(user)/aihub/datasets/page.tsx
  src/app/(user)/aihub/models/AIHub.module.css
  src/app/(user)/aihub/models/page.tsx
  src/components/common/Cards/Aihub/Aihub.module.css
  src/components/common/Cards/Aihub/Aihub.tsx
Labels: feat

#83 [FEAT] 산학협력 프로젝트 문의 페이지
  src/app/(user)/infodesk/inquiries/page.tsx
  src/app/(user)/infodesk/inquiries/projectQA.module.css
  src/app/(user)/infodesk/inquiries/write/page.tsx
  src/app/(user)/infodesk/inquiries/write/writeQA.module.css
  src/components/common/RegisterForm/registerForm.tsx
Labels: feat

#84 [FEAT] 대담영상 페이지 및 비디오카드 퀴즈 모달
  src/app/(user)/infodesk/inquiries/page.tsx
  src/app/(user)/interviews/interviews.module.css
  src/app/(user)/interviews/page.tsx
  src/components/common/VideoCard/QuizModal.tsx
  src/components/common/VideoCard/VideoCard.tsx
Labels: feat

#67 [FEAT] 로그인 페이지 구현 및 로그인 박스 수정
  src/app/(user)/(auth)/login/loginPage.module.css
  src/app/(user)/(auth)/login/page.tsx
  src/components/common/LoginBox/LoginBox.tsx
  src/components/pages/loginPage/loginPage.story.tsx
  src/components/pages/loginPage/loginPage.tsx
Labels: feat

#101 [FIX] ProjectCard 컴포넌트 수정
  src/app/(user)/(auth)/login/loginPage.module.css
  src/app/(user)/(auth)/login/page.tsx
  src/app/(user)/(auth)/register/page.tsx
  src/app/(user)/(auth)/register/registerPage.module.css
  src/app/(user)/aihub/datasets/AIHub.module.css
  src/app/(user)/aihub/datasets/page.tsx
  src/app/(user)/aihub/models/AIHub.module.css
  src/app/(user)/aihub/models/page.tsx
  src/app/(user)/infodesk/inquiries/page.tsx
  src/app/(user)/infodesk/inquiries/projectQA.module.css
  src/app/(user)/infodesk/inquiries/write/page.tsx
  src/app/(user)/infodesk/inquiries/write/writeQA.module.css
  src/app/(user)/interviews/interviews.module.css
  src/app/(user)/interviews/page.tsx
  src/components/common/Cards/Aihub/Aihub.module.css
  src/components/common/Cards/Aihub/Aihub.tsx
  src/components/common/LoginBox/LoginBox.module.css
  src/components/common/LoginBox/LoginBox.story.tsx
  src/components/common/LoginBox/LoginBox.tsx
  src/components/common/LoginBox/index.ts
  src/components/common/ProjectCard/ProjectCard.tsx
  src/components/common/ProjectCard/ProjectCardLikeSection.tsx
  src/components/common/RegisterForm/registerForm.module.css
  src/components/common/RegisterForm/registerForm.tsx
  src/components/common/VideoCard/QuizModal.tsx
  src/components/common/VideoCard/VideoCard.tsx
Labels: bug
