Repository SystemConsultantGroup/S-top-frontend, pull requests merged in 2024-08, with the labels that each got.

#38 [Feat] 대담영상 카드 추가
  src/components/common/VideoCard/VideoCard.module.css
  src/components/common/VideoCard/VideoCard.story.tsx
  src/components/common/VideoCard/VideoCard.test.tsx
  src/components/common/VideoCard/VideoCard.tsx
Labels: feat

#49 [FIX] test colors theme of a component remain
  src/components/common/Footer/Footer.module.css
  src/components/common/Header/Header.module.css
  src/components/common/NoticeDetail/NoticeDetail.module.css
  src/components/common/Noticeboard/Noticeboard.module.css
Labels: bug

#50 [FIX] ease-in-out transition n storybook layout fullscreen
  src/components/common/Header/Header.module.css
  src/components/common/Header/Header.story.tsx
Labels: bug

#14 [FEAT] VR 바로가기 컴포넌트 추가
  public/images/vrlink.png
  src/components/common/VRLink/VRLink.module.css
  src/components/common/VRLink/VRLink.story.tsx
  src/components/common/VRLink/VRLink.tsx
  src/components/common/VRLink/index.ts
Labels: feat

#25 [FEAT] 프로젝트 선택 탭 추가
  src/components/common/Tabs/ProjectSelectTab/ProjectSelectTab.module.css
  src/components/common/Tabs/ProjectSelectTab/ProjectSelectTab.story.tsx
  src/components/common/Tabs/ProjectSelectTab/ProjectSelectTab.test.tsx
  src/components/common/Tabs/ProjectSelectTab/ProjectSelectTab.tsx
  src/components/common/Tabs/index.ts
  src/theme/AppTheme.ts
Labels: feat

#12 [FEAT] 카드 뱃지 컴포넌트 추가
  src/components/common/CardBadge/CardBadge.module.css
  src/components/common/CardBadge/CardBadge.story.tsx
  src/components/common/CardBadge/CardBadge.test.tsx
  src/components/common/CardBadge/CardBadge.tsx
  src/components/common/CardBadge/index.ts
Labels: feat

#54 [BUG] 드롭다운 수정
  src/components/common/Dropdown/Dropdown.story.tsx
  src/components/common/Dropdown/Dropdown.test.tsx
  src/components/common/Dropdown/Dropdown.tsx
Labels: bug

#55 [FIX] 배너오류 수정
  src/components/common/Banner/Banner.module.css
  src/components/common/Banner/Banner.tsx
  src/components/common/VRLink/VRLink.module.css
  src/components/common/VRLink/VRLink.tsx
Labels: bug

#30 [FEAT] 관리자 사이드바 추가
  src/app/admin/layout.module.css
  src/app/admin/layout.tsx
  src/app/admin/page.tsx
  src/app/admin/proposals/page.tsx
  src/components/common/Sidebar/Sidebar.module.css
  src/components/common/Sidebar/Sidebar.tsx
  src/components/common/Sidebar/SidebarItem.module.css
  src/components/common/Sidebar/SidebarItem.tsx
  src/components/common/Sidebar/index.ts
  src/components/pages/AdminSidebar/AdminSidebar.story.tsx
  src/components/pages/AdminSidebar/AdminSidebar.tsx
  src/components/pages/AdminSidebar/AdminSidebarMenu.tsx
  src/components/pages/AdminSidebar/index.ts
Labels: feat

#61 [FIX] 색상 오류 수정
  src/components/common/Footer/Footer.module.css
  src/components/common/Header/Header.module.css
  src/components/common/NoticeDetail/NoticeDetail.module.css
  src/components/common/Noticeboard/Noticeboard.module.css
Labels: bug

#62 [FEAT] 사용자/관리자 페이지 레이아웃 추가
  src/app/(admin)/admin/(boards)/event/notices/page.tsx
  src/app/(admin)/admin/(boards)/notices/page.tsx
  src/app/(admin)/admin/(contents)/gallery/page.tsx
  src/app/(admin)/admin/(contents)/interviews/page.tsx
  src/app/(admin)/admin/(contents)/jobfair/page.tsx
  src/app/(admin)/admin/(contents)/quiz-list/page.tsx
  src/app/(admin)/admin/applications/page.tsx
  src/app/(admin)/admin/event-period/page.tsx
  src/app/(admin)/admin/page.tsx
  src/app/(admin)/admin/projects/[id]/page.tsx
  src/app/(admin)/admin/projects/create/page.tsx
  src/app/(admin)/admin/projects/inquiries/page.tsx
  src/app/(admin)/admin/projects/page.tsx
  src/app/(admin)/admin/projects/proposals/page.tsx
  src/app/(admin)/layout.module.css
  src/app/(admin)/layout.tsx
  src/app/(user)/(auth)/login/page.tsx
  src/app/(user)/(auth)/register/page.tsx
  src/app/(user)/aihub/datasets/page.tsx
  src/app/(user)/aihub/models/page.tsx
  src/app/(user)/event/award/page.tsx
  src/app/(user)/event/gallery/[id]/page.tsx
  src/app/(user)/event/gallery/page.tsx
  src/app/(user)/event/notices/[id]/page.tsx
  src/app/(user)/event/notices/page.tsx
  src/app/(user)/infodesk/cooperation/page.tsx
  src/app/(user)/infodesk/inquiries/page.tsx
  src/app/(user)/infodesk/inquiries/write/page.tsx
  src/app/(user)/infodesk/notices/[id]/page.tsx
  src/app/(user)/infodesk/notices/page.tsx
  src/app/(user)/infodesk/proposals/page.tsx
  src/app/(user)/infodesk/proposals/write/page.tsx
  src/app/(user)/infodesk/s-top/page.tsx
  src/app/(user)/interviews/page.tsx
  src/app/(user)/jobfair/advices/page.tsx
  src/app/(user)/jobfair/interns/page.tsx
  src/app/(user)/jobfair/recruitments/page.tsx
  src/app/(user)/layout.module.css
  src/app/(user)/layout.tsx
  src/app/(user)/mypage/page.tsx
  src/app/(user)/page.tsx
  src/app/(user)/projects/[id]/page.tsx
  src/app/(user)/projects/page.tsx
  src/app/page.tsx
  src/components/pages/AdminSidebar/AdminSidebarMenu.tsx
Labels: enhancement

#65 [FEAT] 서브 네비게이션바
  src/components/common/SubHeadNavbar/NavList.ts
  src/components/common/SubHeadNavbar/SubHeadNavbar.module.css
  src/components/common/SubHeadNavbar/SubHeadNavbar.story.tsx
  src/components/common/SubHeadNavbar/SubHeadNavbar.test.tsx
  src/components/common/SubHeadNavbar/SubHeadNavbar.tsx
Labels: feat

#58 [FEAT] 로그인, 로그아웃 모듈 추가
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/login/kakao/page.tsx
  src/components/common/Auth/AuthProvider.tsx
  src/components/common/Auth/getServerSideToken.ts
  src/components/common/Auth/index.ts
  src/components/common/DataTable/DataTableUsage.tsx
  src/components/pages/KakaoAuth/KakaoAuth.tsx
  src/components/pages/KakaoAuth/index.ts
  src/constants/Auth.ts
  src/types/.gitkeep
  src/types/jwtPayload.ts
  src/types/user.ts
  src/utils/CommonAxios/CommonAxios.ts
  src/utils/CommonAxios/index.ts
  src/utils/fetcher/fetcher.ts
  src/utils/fetcher/index.ts
Labels: enhancement

#75 [FIX] App Theme 색상 수정
  src/components/common/Dropdown/Dropdown.module.css
  src/theme/AppTheme.ts
Labels: fix

#82 [FIX] 갤러리 미리보기 컴포넌트 버그 수정
  package-lock.json
  src/components/common/GalleryPreview/GalleryPreview.module.css
  src/components/common/GalleryPreview/GalleryPreview.tsx
Labels: bug

#70 [FIX] 버튼 컴포넌트 사용성 개선
  package-lock.json
  package.json
  src/components/common/Buttons/DangerButton/DangerButton.story.tsx
  src/components/common/Buttons/DangerButton/DangerButton.test.tsx
  src/components/common/Buttons/DangerButton/DangerButton.tsx
  src/components/common/Buttons/OutlinedButton/OutlinedButton.story.tsx
  src/components/common/Buttons/OutlinedButton/OutlinedButton.test.tsx
  src/components/common/Buttons/OutlinedButton/OutlinedButton.tsx
  src/components/common/Buttons/PrimaryButton/PrimaryButton.story.tsx
  src/components/common/Buttons/PrimaryButton/PrimaryButton.test.tsx
  src/components/common/Buttons/PrimaryButton/PrimaryButton.tsx
  src/components/common/Buttons/SecondaryButton/SecondaryButton.story.tsx
  src/components/common/Buttons/SecondaryButton/SecondaryButton.test.tsx
  src/components/common/Buttons/SecondaryButton/SecondaryButton.tsx
Labels: fix

#89 [FIX] TextInput과 VRLink 각각 스타일 수정
  package-lock.json
  src/components/common/Buttons/PrimaryButton/PrimaryButton.test.tsx
  src/components/common/TextInput/TextInput.tsx
  src/components/common/VRLink/VRLink.module.css
Labels: fix

#77 [FIX] 비디오카드 수정
  src/components/common/VideoCard/VideoCard.story.tsx
  src/components/common/VideoCard/VideoCard.test.tsx
  src/components/common/VideoCard/VideoCard.tsx
Labels: bug, fix

#90 [FEAT] JobFair 페이지 추가
  src/app/(admin)/admin/(boards)/notices/page.tsx
  src/app/(user)/jobfair/advices/jobfair.module.css
  src/app/(user)/jobfair/advices/page.tsx
  src/app/(user)/jobfair/interns/jonfairInterns.module.css
  src/app/(user)/jobfair/interns/page.tsx
  src/app/(user)/jobfair/recruitments/jobfairRe.module.css
  src/app/(user)/jobfair/recruitments/page.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Header/Header.module.css
  src/components/common/Header/NavList.ts
  src/components/common/Header/elements/HandoutOverview.tsx
  src/components/common/Header/elements/HeaderTopNav.tsx
  src/components/common/Noticeboard/Noticeboard.story.tsx
  src/components/common/Noticeboard/Noticeboard.test.tsx
  src/components/common/Noticeboard/Noticeboard.tsx
  src/components/common/Noticeboard/elements/NoticeContainer.tsx
  src/components/common/Noticeboard/elements/NoticeHeading.tsx
  src/components/common/Noticeboard/elements/NoticeItem.tsx
  src/components/common/Pagination/Pagination.stories.tsx
  src/components/common/Pagination/Pagination.test.tsx
  src/components/common/Pagination/Pagination.tsx
  src/components/common/Pagination/index.ts
  src/components/common/SubHeadNavbar/SubHeadNavbar.tsx
  src/components/common/SubHeadNavbar/index.ts
  src/components/common/VRLink/VRLink.module.css
  src/components/common/VideoCard/VideoCard.tsx
  src/components/pages/projects/jobfair.module.css
  src/components/pages/projects/jobfair.stories.tsx
  src/components/pages/projects/jobfair.tsx
  src/constants/UserNavigations.ts
  src/types/MantineTypes.ts
  src/types/PageBoardTypes.ts
Labels: feat
