Repository SystemConsultantGroup/S-top-frontend, pull requests merged in 2025-02, with the labels that each got.

#154 [FIX] 프로젝트 카드 라우팅 경로 수정
  src/components/common/ProjectCard/ProjectCard.tsx
Labels: bug

#156 [fix] CI env kakao client id NEXT_PUBLIC prefix
  .github/workflows/CI.yml
Labels: fix

#157 [fix] login client id prefix edit
  src/components/common/LoginBox/LoginBox.tsx
Labels: fix

#164 [fix] interview layout + videocard modal fix
  src/app/(user)/interviews/interviews.module.css
  src/app/(user)/interviews/page.tsx
  src/components/common/VideoCard/DetailModal.tsx
  src/components/common/VideoCard/QuizModal.tsx
  src/components/common/VideoCard/VideoCard.tsx
Labels: fix

#167 [FIX] 미사용 프로젝트 문의 버튼 제거
  src/app/(user)/projects/[id]/page.tsx
  src/components/pages/ProjectDetail/ProjectDetailInquiry.tsx
Labels: fix

#174 [FIX] (이벤트)공지사항 및 갤러리 시간 표기 수정
  src/app/(user)/page.tsx
  src/components/common/Noticeboard/elements/NoticeItem.tsx
Labels: bug

#183 [fix] header login 새로고침 수정, 모바일에서 보이게 변경
  src/components/common/Auth/AuthProvider.tsx
  src/components/common/Header/Header.module.css
  src/components/common/Header/elements/HeaderToolBar.tsx
Labels: fix

#186 공지사항을 비롯한 게시판형 UI 에서 모바일 사용성을 개선합니다.
  src/app/(user)/infodesk/inquiries/projectQA.module.css
  src/components/common/Noticeboard/Noticeboard.module.css
  src/styles/UserBoard.module.css
Labels: bug, fix

#197 대담 영상 퀴즈 모달에서 선지 선택 시 스크롤이 불가해지는 문제를 수정합니다.
  src/components/common/VideoCard/VideoCard.tsx
Labels: bug

#200 카카오 로그인 하고 처음으로 돌아온 직후 Loading 표시 지속되고 이름 표시 안 되는 문제 임시로 해결
  src/utils/fetcher/fetcher.ts
Labels: bug

#201 AuthProvider 의 로그인 함수 호출로 인한 무한 리렌더링 이슈 해결
  src/components/common/Auth/AuthProvider.tsx
Labels: bug

#204 fix: accessToken 이 없는 경우 undefined 대신 null 을 보내어 에러를 해결한다
  src/utils/fetcher/fetcher.ts
Labels: bug

#205 fix: /interview 페이지에서 대담 영상 북마크 작동 하지 않는 문제 해결
  src/app/(user)/interviews/page.tsx
Labels: bug

#211 [HOTFIX] 학장님 성함 추가
  src/app/(user)/infodesk/s-top/page.tsx
Labels: bug, fix

#212 [HOTFIX] 학장님 성함 추가 prod 배포용
  src/app/(user)/infodesk/s-top/page.tsx
Labels: bug, fix

#217 [FIX] 프로젝트 페이지 탭이동시 좋아요, 북마크 등 고정되어있는 버그 수정
  src/components/common/ProjectCard/ProjectCardLikeSection.tsx
Labels: bug

#218 [FIX] 프로젝트 상세보기 페이지 좋아요, 북마크 표시 오류 수정
  src/components/common/ProjectCard/ProjectCardLikeSection.tsx
  src/components/pages/ProjectDetail/ProjectDetailInfo.tsx
Labels: bug

#223 [FIX] user id 없는 4000번 에러 코드에 대해서도 로그아웃 대응 시도
  src/components/common/Header/Header.tsx
Labels: fix

#224 [HOTFIX] 토큰 문제에 대한 로그아웃 대응, 댓글 익명이름 수정, 외부인 핸들링
  src/components/common/CommentBox/CommentBox.tsx
  src/components/common/Header/Header.tsx
  src/constants/LookupTables.ts
  src/constants/LookupTables/USER_TYPE_LOOKUP_TABLE.ts
  src/types/user.ts
Labels: fix

#227 [FIX] Interceptor에 있는 오류 if문 순서 수정
  src/utils/CommonAxios/CommonAxios.ts
Labels: bug, fix
