Repository SystemConsultantGroup/S-top-frontend, pull requests merged in 2025-01, with the labels that each got.

#106 [FEAT] 프로젝트 상세조회 페이지 API 연결
  src/app/(user)/projects/[id]/page.tsx
  src/components/common/CommentBox/CommentBox.module.css
  src/components/common/CommentBox/CommentBox.tsx
  src/components/pages/ProjectDetail/ProjectDetailComment.tsx
  src/components/pages/ProjectDetail/ProjectDetailInfo.module.css
  src/components/pages/ProjectDetail/ProjectDetailInfo.tsx
  src/components/pages/ProjectDetail/ProjectDetailInquiry.tsx
  src/components/pages/ProjectDetail/_type/comment.ts
  src/components/pages/ProjectDetail/_type/project.ts
Labels: enhancement, feat

#108 [feat] AI HUB 노션 연결
  src/app/(user)/aihub/datasets/page.tsx
  src/app/(user)/aihub/models/page.tsx
  src/app/(user)/infodesk/inquiries/[id]/page.tsx
  src/app/(user)/infodesk/inquiries/page.tsx
  src/app/(user)/infodesk/inquiries/write/page.tsx
  src/app/(user)/infodesk/inquiries/write/writeQA.module.css
  src/app/(user)/interviews/interviews.module.css
  src/app/(user)/interviews/page.tsx
  src/components/common/VideoCard/QuizModal.tsx
  src/components/common/VideoCard/VideoCard.tsx
Labels: feat

#124 [feat] AIHUB notion backend 연결 수정
  src/app/(user)/aihub/datasets/page.tsx
  src/app/(user)/aihub/models/page.tsx
Labels: feat, fix

#107 [FEAT] 마이페이지 개발
  package-lock.json
  src/app/(user)/mypage/page.module.css
  src/app/(user)/mypage/page.tsx
  src/components/common/Dropdown/Dropdown.module.css
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/VideoCard/VideoCard.tsx
  src/components/pages/AdminProjectsEditSection/ProjectCreateSection.tsx
  src/components/pages/MyPage/Mypage.module.css
  src/components/pages/MyPage/MypageForm.module.css
  src/components/pages/MyPage/MypageForm.tsx
  src/components/pages/MyPage/MypageInterest.tsx
  src/components/pages/MyPage/MypageTable.module.css
  src/components/pages/MyPage/MypageTable.tsx
  src/components/pages/MyPage/MypageUserInfo.tsx
  src/components/pages/MyPage/_mock/mock-user.tsx
  src/types/user.ts
Labels: feat

#141 [FIX] NoticeBoard 컴포넌트 수정
  src/components/common/Noticeboard/elements/NoticeItem.tsx
  src/types/PageBoardTypes.ts
Labels: fix

#142 [FIX] VideoCard 제목 text-overflow 처리
  src/components/common/VideoCard/VideoCard.module.css
Labels: fix

#143 [FIX] aihub model merge code edit, inquires fix
  src/app/(user)/aihub/models/page.tsx
  src/app/(user)/infodesk/inquiries/page.tsx
Labels: bug, fix

#147 [fix] user navigation inquiries not inquries
  src/constants/UserNavigations.ts
Labels: fix

#148 [HOTFIX] 빌드 오류 해결
  package.json
  src/app/(user)/infodesk/proposals/page.tsx
  src/components/pages/AdminProposalsListSection/AdminProposalsListSection.tsx
Labels: bug

#150 변경사항 반영을 위해 머지합니다.
  package.json
Labels: bug
